In [1]:
import polars as ps
import matplotlib.pyplot as plt

In [2]:
train_path = "titanic/train.csv"
test_path = "titanic/test.csv"

In [10]:
train_df = ps.read_csv(train_path)
y = train_df["Survived"]
train_df = train_df.drop(["Survived"])
train_df

shape: (891, 11)
┌─────────────┬────────┬──────────────────┬────────┬─────┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Pclass ┆ Name             ┆ Sex    ┆ ... ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---    ┆ ---              ┆ ---    ┆     ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64    ┆ str              ┆ str    ┆     ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪════════╪══════════════════╪════════╪═════╪════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 3      ┆ Braund, Mr. Owen ┆ male   ┆ ... ┆ A/5 21171  ┆ 7.25    ┆ null  ┆ S        │
│             ┆        ┆ Harris           ┆        ┆     ┆            ┆         ┆       ┆          │
│ 2           ┆ 1      ┆ Cumings, Mrs.    ┆ female ┆ ... ┆ PC 17599   ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆        ┆ John Bradley     ┆        ┆     ┆            ┆         ┆       ┆          │
│             ┆        ┆ (Flor...         ┆        ┆     ┆            ┆         ┆       ┆          │
│ 3           ┆ 3      ┆ Heikkinen, Miss. ┆ female ┆ ... ┆ STON/O2.   ┆ 7.925   ┆ null  ┆ S        │
│             ┆        ┆ Laina            ┆        ┆     ┆ 3101282    ┆         ┆       ┆          │
│ 4           ┆ 1      ┆ Futrelle, Mrs.   ┆ female ┆ ... ┆ 113803     ┆ 53.1    ┆ C123  ┆ S        │
│             ┆        ┆ Jacques Heath    ┆        ┆     ┆            ┆         ┆       ┆          │
│             ┆        ┆ (Li...           ┆        ┆     ┆            ┆         ┆       ┆          │
│ ...         ┆ ...    ┆ ...              ┆ ...    ┆ ... ┆ ...        ┆ ...     ┆ ...   ┆ ...      │
│ 888         ┆ 1      ┆ Graham, Miss.    ┆ female ┆ ... ┆ 112053     ┆ 30.0    ┆ B42   ┆ S        │
│             ┆        ┆ Margaret Edith   ┆        ┆     ┆            ┆         ┆       ┆          │
│ 889         ┆ 3      ┆ Johnston, Miss.  ┆ female ┆ ... ┆ W./C. 6607 ┆ 23.45   ┆ null  ┆ S        │
│             ┆        ┆ Catherine Helen  ┆        ┆     ┆            ┆         ┆       ┆          │
│             ┆        ┆ ...              ┆        ┆     ┆            ┆         ┆       ┆          │
│ 890         ┆ 1      ┆ Behr, Mr. Karl   ┆ male   ┆ ... ┆ 111369     ┆ 30.0    ┆ C148  ┆ C        │
│             ┆        ┆ Howell           ┆        ┆     ┆            ┆         ┆       ┆          │
│ 891         ┆ 3      ┆ Dooley, Mr.      ┆ male   ┆ ... ┆ 370376     ┆ 7.75    ┆ null  ┆ Q        │
│             ┆        ┆ Patrick          ┆        ┆     ┆            ┆         ┆       ┆          │
└─────────────┴────────┴──────────────────┴────────┴─────┴────────────┴─────────┴───────┴──────────┘